### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by River-Zhang** [wbjang/nvist_official#1]
Thanks for your great work!
I was wondering what the time cost is when inputting an in-the-wild image and outputs a novel view. Besides, what is the FPS of the rendering? Thanks very much!

**Comment by wbjang** [comment]
Hello @River-Zhang,

Thank you for the message. 
I have not measured FPS but it is pretty fast - around 1 FPS I assume. Once you build vector-matrix representation, you do not have to reconstruct it again for other viewpoints, so there is a potential for speed improvement.

Cheers,
Wonbong

**Comment by River-Zhang** [comment]
I got it. Thanks very much！
